name: QuarterBukkit
version: Beta 1.0.6
description: QuarterBukkit is an API extension for Bukkit
authors: [QuarterCode, LoadingByte]
website: http://dev.bukkit.org/server-mods/QuarterBukkit
main: com.quartercode.quarterbukkit.QuarterBukkit
load: startup